

# Base Training
mkdir -p /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1; 
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 4 --anatomy-only brain -b 1 --start-epoch 0 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain False --retrain-epoch 5 --use-random-mask False --random-mask-prop 0.5 --betas 0.9 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 0.0003 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1 > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1/acc4-brain.log 2>&1;
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 4 --anatomy-only knee -b 1 --start-epoch 0 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain False --retrain-epoch 5 --use-random-mask False --random-mask-prop 0.5 --betas 0.9 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 0.0003 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1 > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1/acc4-knee.log 2>&1;
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 8 --anatomy-only brain -b 1 --start-epoch 0 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain False --retrain-epoch 5 --use-random-mask False --random-mask-prop 0.5 --betas 0.9 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 0.0003 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1 > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1/acc8-brain.log 2>&1;
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 8 --anatomy-only knee -b 1 --start-epoch 0 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain False --retrain-epoch 5 --use-random-mask False --random-mask-prop 0.5 --betas 0.9 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 0.0003 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1 > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1/acc8-knee.log 2>&1;
sleep 30;

# First Retraining
mkdir -p /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain; 
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 4 --anatomy-only brain -b 1 --start-epoch 5 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 3e-04 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc4-brain.log 2>&1
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 4 --anatomy-only knee -b 1 --start-epoch 5 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 3e-04 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc4-knee.log 2>&1;
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 8 --anatomy-only brain -b 1 --start-epoch 5 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 3e-04 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc8-brain.log 2>&1; 
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 8 --anatomy-only knee -b 1 --start-epoch 5 -e 5 --accumulation-step 2 --criterion AnatomicalSSIM --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler cosine -m fivarnet --lr 3e-04 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc8-knee.log 2>&1;
sleep 30;
mv /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain1


# Second Retraining 
mkdir -p /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain; 
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 4 --anatomy-only brain -b 1 --start-epoch 10 -e 5 --accumulation-step 2 --criterion SobelLoss --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler constant -m fivarnet --lr 1e-05 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc4-brain.log 2>&1
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 4 --anatomy-only knee -b 1 --start-epoch 10 -e 5 --accumulation-step 2 --criterion SobelLoss --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler constant -m fivarnet --lr 1e-05 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc4-knee.log 2>&1;
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 8 --anatomy-only brain -b 1 --start-epoch 10 -e 5 --accumulation-step 2 --criterion SobelLoss --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler constant -m fivarnet --lr 1e-05 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc8-brain.log 2>&1; 
sleep 30;
python -u /root/FastMRI_challenge/train.py -g 0 --acc-only 8 --anatomy-only knee -b 1 --start-epoch 10 -e 5 --accumulation-step 2 --criterion SobelLoss --retrain True --retrain-epoch 5 --use-random-mask True --random-mask-prop 0.5 --betas 0.2 0.999 --model fivarnet -f 8 -i 2 -a 0 --chans 32 --sens-chans 8 --use-moe True --slice-moe 1 --class-split-path /root/FastMRI_challenge/class_indices --k-fold True --num-folds 5 --data-augmentation False --data-path-train /root/Data/train --data-path-val /root/Data/val --scheduler constant -m fivarnet --lr 1e-05 --lr-min1 5e-05 --lr-max2 0.00015 --lr-min2 0.0 --warmup1 10 --anneal1 40 --warmup2 10 --anneal2 40 --seed 2025 --result-path /root/FastMRI_challenge/results --report-interval 100 -n fivarnet_f8_i2_attn0_c32_s8_base__epoch5_fold5_slice1_retrain > /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain/acc8-knee.log 2>&1;
sleep 30;
mv /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain /root/FastMRI_challenge/results/fivarnet_f8_i2_attn0_c32_s8_base/epoch5_fold5_slice1_retrain2

